com:
  xt:
    legend:
      filters:
        login: /login
        logout: /logout
        anon:
          - /login
          - /logout
          - /static/**
        authc:
          - /**

server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
